language: python
matrix:
  include:
    - python: 2.6
      env: TOXENV=py26
    - python: 3.6
      env: TOXENV=py36
    - python: pypy
      env: TOXENV=pypy
install:
  - pip install tox
script:
  - tox -e $TOXENV
