---

version: 2.1

executors:
  python-27: {docker: [{image: 'circleci/python:2.7'}]}
  python-33: {docker: [{image: 'circleci/python:3.3'}]}
  python-34: {docker: [{image: 'circleci/python:3.4'}]}
  python-35: {docker: [{image: 'circleci/python:3.5'}]}
  python-36: {docker: [{image: 'circleci/python:3.6'}]}
  python-37: {docker: [{image: 'circleci/python:3.7'}]}

jobs:
  build:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-<< parameters.executor >>-{{ checksum "requirements.txt" }}
        - v1-dependencies-<< parameters.executor >>
    - run:
        name: install dependencies
        command: |
          python -m venv venv
          . venv/bin/activate
          python setup.py install
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-<< parameters.executor >>-{{ checksum "requirements.txt" }}
    - run:
        name: run tests
        command: |
          . venv/bin/activate
          python setup.py test

workflows:
  run-tests:
    jobs:
    - build: {name: run-tests-python-2.7, executor: python-27}
    - build: {name: run-tests-python-3.3, executor: python-33}
    - build: {name: run-tests-python-3.5, executor: python-34}
    - build: {name: run-tests-python-3.5, executor: python-35}
    - build: {name: run-tests-python-3.6, executor: python-36}
    - build: {name: run-tests-python-3.7, executor: python-37}
