---

version: 2.1

executors:
  python-2.6: {docker: [{image: 'circleci/python:2.6'}]}
  python-2.7: {docker: [{image: 'circleci/python:2.7'}]}
  python-3.0: {docker: [{image: 'circleci/python:3.0'}]}
  python-3.1: {docker: [{image: 'circleci/python:3.1'}]}
  python-3.2: {docker: [{image: 'circleci/python:3.2'}]}
  python-3.3: {docker: [{image: 'circleci/python:3.3'}]}
  python-3.4: {docker: [{image: 'circleci/python:3.4'}]}
  python-3.5: {docker: [{image: 'circleci/python:3.5'}]}
  python-3.6: {docker: [{image: 'circleci/python:3.6'}]}
  python-3.7: {docker: [{image: 'circleci/python:3.7'}]}

jobs:
  build:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-
    - run:
        name: install dependencies
        command: |
          python -m venv venv
          . venv/bin/activate
          python setup.py install
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}
    - run:
        name: run tests
        command: |
          . venv/bin/activate
          python setup.py test

workflows:
  run-tests:
    jobs:
    - build: {name: run-tests-python-2.6, executor: python-2.6}
    - build: {name: run-tests-python-2.7, executor: python-2.7}
    - build: {name: run-tests-python-3.0, executor: python-3.0}
    - build: {name: run-tests-python-3.1, executor: python-3.1}
    - build: {name: run-tests-python-3.2, executor: python-3.2}
    - build: {name: run-tests-python-3.3, executor: python-3.3}
    - build: {name: run-tests-python-3.5, executor: python-3.4}
    - build: {name: run-tests-python-3.5, executor: python-3.5}
    - build: {name: run-tests-python-3.6, executor: python-3.6}
    - build: {name: run-tests-python-3.7, executor: python-3.7}
